"""thêm cột lất_active cho bảng users  

Revision ID: 149e696a483d
Revises: f7db58bad85e
Create Date: 2025-08-07 08:36:47.175150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149e696a483d'
down_revision = 'f7db58bad85e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('LanCuoiHoatDong', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('LanCuoiHoatDong')

    # ### end Alembic commands ###
