"""thêm bảng orderLogs  

Revision ID: 1796837762ab
Revises: e5eb5aff0c52
Create Date: 2025-08-13 15:06:35.615771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1796837762ab'
down_revision = 'e5eb5aff0c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrderLogs',
    sa.Column('LogID', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('MaNguoiDung', sa.Integer(), nullable=False),
    sa.Column('MaDonHang', sa.Integer(), nullable=False),
    sa.Column('HanhDong', sa.Unicode(length=100, collation='Vietnamese_CI_AS'), nullable=False),
    sa.Column('MoTa', sa.Unicode(length=100, collation='Vietnamese_CI_AS'), nullable=True),
    sa.Column('ThoiGian', sa.DateTime(), server_default=sa.text('(getdate())'), nullable=False),
    sa.ForeignKeyConstraint(['MaDonHang'], ['Orders.MaDonHang'], name='FK__OrderLogs__MaDonHang'),
    sa.ForeignKeyConstraint(['MaNguoiDung'], ['Users.MaNguoiDung'], name='FK__OrderLogs__MaNguoiDung'),
    sa.PrimaryKeyConstraint('LogID', name='PK__OrderLogs')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrderLogs')
    # ### end Alembic commands ###
