"""thêm cột mã giảm giá cho orders

Revision ID: 1d0a84b175fd
Revises: b21b936cb9cb
Create Date: 2025-09-04 20:51:57.760216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '1d0a84b175fd'
down_revision = 'b21b936cb9cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    with op.batch_alter_table('DonHang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MaGiamGia', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('FK__Orders__MaGiamGia', 'MaGiamGia', ['MaGiamGia'], ['MaGiamGia'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DonHang', schema=None) as batch_op:
        batch_op.drop_constraint('FK__Orders__MaGiamGia', type_='foreignkey')
        batch_op.drop_column('MaGiamGia')

    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B613089ECE8'))
    )
    # ### end Alembic commands ###
