"""Thêm bảng adminLogs 

Revision ID: 22a962164928
Revises: c0e1fe19b6a6
Create Date: 2025-08-25 20:30:00.662678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a962164928'
down_revision = 'c0e1fe19b6a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AdminLogs',
    sa.Column('MaNhatKy', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('MaAdmin', sa.Integer(), nullable=True),
    sa.Column('HanhDong', sa.Unicode(length=255, collation='Vietnamese_CI_AS'), nullable=True),
    sa.Column('MoTa', sa.Unicode(length=255, collation='Vietnamese_CI_AS'), nullable=True),
    sa.Column('ThoiGian', sa.DateTime(), server_default=sa.text('(getdate())'), nullable=True),
    sa.ForeignKeyConstraint(['MaAdmin'], ['Admins.MaAdmin'], ),
    sa.PrimaryKeyConstraint('MaNhatKy')
    )
    with op.batch_alter_table('ActivityLogs', schema=None) as batch_op:
        batch_op.drop_column('DiaChiIP')

    with op.batch_alter_table('Admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('HoTen', sa.Unicode(length=100, collation='Vietnamese_CI_AS'), server_default=sa.text("N'Chưa cập nhật'"), nullable=True))
        batch_op.add_column(sa.Column('AnhDaiDien', sa.Unicode(length=255, collation='Vietnamese_CI_AS'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Admins', schema=None) as batch_op:
        batch_op.drop_column('AnhDaiDien')
        batch_op.drop_column('HoTen')

    with op.batch_alter_table('ActivityLogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DiaChiIP', sa.NVARCHAR(length=50, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True))

    op.drop_table('AdminLogs')
    # ### end Alembic commands ###
