"""thêm cột cho bảng avtivityLog  

Revision ID: 28dbb3baae1d
Revises: 149e696a483d
Create Date: 2025-08-07 13:42:52.830729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28dbb3baae1d'
down_revision = '149e696a483d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActivityLogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MoTa', sa.Unicode(length=255, collation='Vietnamese_CI_AS'), nullable=True))
        batch_op.add_column(sa.Column('DiaChiIP', sa.Unicode(length=50, collation='Vietnamese_CI_AS'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActivityLogs', schema=None) as batch_op:
        batch_op.drop_column('DiaChiIP')
        batch_op.drop_column('MoTa')

    # ### end Alembic commands ###
