"""Đổi khóa chính  cho bảng CartItems  

Revision ID: 2ca5a37aa5ec
Revises: d480a6c91280
Create Date: 2025-07-22 16:00:29.774977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca5a37aa5ec'
down_revision = 'd480a6c91280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CartItems', schema=None) as batch_op:
        batch_op.alter_column('MaGioHang',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('MaSanPham',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('MaChiTietGioHang')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CartItems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MaChiTietGioHang', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))
        batch_op.alter_column('MaSanPham',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('MaGioHang',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
