"""Sửa bảng addresss 

Revision ID: 542ad82afc17
Revises: fbd0b2c446ce
Create Date: 2025-07-25 15:49:14.526689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542ad82afc17'
down_revision = 'fbd0b2c446ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserAddresses', schema=None) as batch_op:
        batch_op.drop_column('TinhThanh')
        batch_op.drop_column('QuanHuyen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserAddresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('QuanHuyen', sa.NVARCHAR(length=100, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('TinhThanh', sa.NVARCHAR(length=100, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
