"""Sửa bảng review

Revision ID: 54e1925bd7db
Revises: b0343ac8331c
Create Date: 2025-09-12 19:32:35.198522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e1925bd7db'
down_revision = 'b0343ac8331c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DanhGia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MaChiTietDonHang', sa.Integer(), nullable=False))
        batch_op.alter_column('DiemDanhGia',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('FK__Reviews__MaDonHa__73ABCDEF'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ChiTietDonHang', ['MaChiTietDonHang'], ['MaChiTietDonHang'])
        batch_op.drop_column('MaDonHang')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DanhGia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MaDonHang', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK__Reviews__MaDonHa__73ABCDEF'), 'DonHang', ['MaDonHang'], ['MaDonHang'])
        batch_op.alter_column('DiemDanhGia',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('MaChiTietDonHang')

    # ### end Alembic commands ###
