"""xóa bảng sơ đồ hệ thống 

Revision ID: 55f37ba4ab9a
Revises: rename_to_vietnamese
Create Date: 2025-08-31 19:40:06.221185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '55f37ba4ab9a'
down_revision = 'rename_to_vietnamese'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SodoHeThong')
    with op.batch_alter_table('OTP', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_email'))
        batch_op.create_index(batch_op.f('ix_OTP_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('OTP', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_OTP_email'))
        batch_op.create_index(batch_op.f('ix_otp_email'), ['email'], unique=False)

    op.create_table('SodoHeThong',
    sa.Column('name', sa.NVARCHAR(length=128, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B6156749D6D'))
    )
    # ### end Alembic commands ###
