"""Thay đổi khóa chính ProductVariant 

Revision ID: 8e84bdd311a2
Revises: a507ed0f0dbd
Create Date: 2025-07-22 08:55:00.846866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e84bdd311a2'
down_revision = 'a507ed0f0dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProductVariants', schema=None) as batch_op:
        batch_op.alter_column('MaSanPham',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('KichThuoc',
               existing_type=sa.NVARCHAR(length=10, collation='Vietnamese_CI_AS'),
               nullable=False)
        batch_op.alter_column('MauSac',
               existing_type=sa.NVARCHAR(length=30, collation='Vietnamese_CI_AS'),
               nullable=False)
        batch_op.alter_column('SoLuongTon',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('((0))'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProductVariants', schema=None) as batch_op:
        batch_op.alter_column('SoLuongTon',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('MauSac',
               existing_type=sa.NVARCHAR(length=30, collation='Vietnamese_CI_AS'),
               nullable=True)
        batch_op.alter_column('KichThuoc',
               existing_type=sa.NVARCHAR(length=10, collation='Vietnamese_CI_AS'),
               nullable=True)
        batch_op.alter_column('MaSanPham',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
