"""Thêm bảng FlashSale_Product

Revision ID: 93ce71faad25
Revises: 54e1925bd7db
Create Date: 2025-09-19 09:05:33.525922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ce71faad25'
down_revision = '54e1925bd7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('KhuyenMaiNong',
    sa.Column('MaKhuyenMai', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('TenKhuyenMai', sa.Unicode(collation='Vietnamese_CI_AS'), nullable=True),
    sa.Column('GiaGiam', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('NgayBatDau', sa.DateTime(), nullable=False),
    sa.Column('NgayKetThuc', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('MaKhuyenMai', name='PK_KhuyenMaiNong')
    )
    op.create_table('KhuyenMaiNong_SanPham',
    sa.Column('MaKhuyenMai', sa.Integer(), nullable=False),
    sa.Column('MaSanPham', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MaKhuyenMai'], ['KhuyenMaiNong.MaKhuyenMai'], ),
    sa.ForeignKeyConstraint(['MaSanPham'], ['SanPham.MaSanPham'], ),
    sa.PrimaryKeyConstraint('MaKhuyenMai', 'MaSanPham', name='PK_KhuyenMaiNong_SanPham')
    )
    with op.batch_alter_table('SanPham', schema=None) as batch_op:
        batch_op.alter_column('NgayTao',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SanPham', schema=None) as batch_op:
        batch_op.alter_column('NgayTao',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))

    op.drop_table('KhuyenMaiNong_SanPham')
    op.drop_table('KhuyenMaiNong')
    # ### end Alembic commands ###
