"""Add new column MoTaNgan for table Product

Revision ID: a507ed0f0dbd
Revises: b9b40de2dcc9
Create Date: 2025-07-22 07:45:27.855546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a507ed0f0dbd'
down_revision = 'b9b40de2dcc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MoTaNgan', sa.Unicode(collation='Vietnamese_CI_AS'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.drop_column('MoTaNgan')

    # ### end Alembic commands ###
