"""thêm cột đã sử dụng mã giảm giấ

Revision ID: a740ee590519
Revises: 1d0a84b175fd
Create Date: 2025-09-05 14:34:55.110360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a740ee590519'
down_revision = '1d0a84b175fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NguoiDung_MaGiamGia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DaSuDung', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NguoiDung_MaGiamGia', schema=None) as batch_op:
        batch_op.drop_column('DaSuDung')

    # ### end Alembic commands ###
