"""Sửa bảng review

Revision ID: b0343ac8331c
Revises: fbd917570cbd
Create Date: 2025-09-12 19:26:08.467962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0343ac8331c'
down_revision = 'fbd917570cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DanhGia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MaDonHang', sa.Integer(), nullable=False))
        batch_op.alter_column('MaNguoiDung',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('MaSanPham',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('DiemDanhGia',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('NgayDanhGia',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))
        batch_op.create_foreign_key('FK__Reviews__MaDonHa__73ABCDEF', 'DonHang', ['MaDonHang'], ['MaDonHang'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DanhGia', schema=None) as batch_op:
        batch_op.drop_constraint('FK__Reviews__MaDonHa__73ABCDEF', type_='foreignkey')
        batch_op.alter_column('NgayDanhGia',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
        batch_op.alter_column('DiemDanhGia',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('MaSanPham',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('MaNguoiDung',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('MaDonHang')

    # ### end Alembic commands ###
