"""thêm bảng vouchers

Revision ID: b21b936cb9cb
Revises: 55a29c179937
Create Date: 2025-09-03 20:12:33.078782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21b936cb9cb'
down_revision = '55a29c179937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NguoiDung_MaGiamGia',
    sa.Column('MaUserCoupon', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('MaNguoiDung', sa.Integer(), nullable=False),
    sa.Column('MaGiamGia', sa.Integer(), nullable=False),
    sa.Column('NgayNhan', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['MaGiamGia'], ['MaGiamGia.MaGiamGia'], name='FK__Coupon__UserCoupon'),
    sa.ForeignKeyConstraint(['MaNguoiDung'], ['NguoiDung.MaNguoiDung'], name='FK__User__UserCoupon'),
    sa.PrimaryKeyConstraint('MaUserCoupon', name='PK__UserCoupon__B4DC79FF')
    )
    with op.batch_alter_table('MaGiamGia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MoTa', sa.Unicode(length=255, collation='Vietnamese_CI_AS'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MaGiamGia', schema=None) as batch_op:
        batch_op.drop_column('MoTa')

    op.drop_table('NguoiDung_MaGiamGia')
    # ### end Alembic commands ###
