"""Initial migration

Revision ID: b9b40de2dcc9
Revises: 
Create Date: 2025-07-21 21:31:37.501720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b40de2dcc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.drop_column('SoLuongTon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SoLuongTon', sa.INTEGER(), server_default=sa.text('((0))'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
