"""Xóa cột Phương thức thanh toán bảng Order 

Revision ID: c0dcf2156ded
Revises: fcb703ecddf2
Create Date: 2025-07-29 08:45:26.157041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0dcf2156ded'
down_revision = 'fcb703ecddf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.drop_column('PhuongThucThanhToan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PhuongThucThanhToan', sa.NVARCHAR(length=50, collation='Vietnamese_CI_AS'), server_default=sa.text("(N'COD')"), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
