"""Thêm cột Phương thức thanh toán cho bảng Orders  

Revision ID: c8d28ed10bb1
Revises: 542ad82afc17
Create Date: 2025-07-28 16:37:08.155327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d28ed10bb1'
down_revision = '542ad82afc17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PhuongThucThanhToan', sa.Unicode(length=50, collation='Vietnamese_CI_AS'), server_default=sa.text("(N'COD')"), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.drop_column('PhuongThucThanhToan')

    # ### end Alembic commands ###
