"""Thêm 2 cột  cho bảng OrderDetails  

Revision ID: caa277fa971a
Revises: 2ca5a37aa5ec
Create Date: 2025-07-23 16:15:35.310726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa277fa971a'
down_revision = '2ca5a37aa5ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('OrderDetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('KichThuoc', sa.Unicode(length=10, collation='Vietnamese_CI_AS'), server_default=sa.text("'M'"), nullable=False))
        batch_op.add_column(sa.Column('MauSac', sa.Unicode(length=30, collation='Vietnamese_CI_AS'), server_default=sa.text("N'Trắng'"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('OrderDetails', schema=None) as batch_op:
        batch_op.drop_column('MauSac')
        batch_op.drop_column('KichThuoc')

    # ### end Alembic commands ###
