"""Thêm cột  cho bảng CartItems  

Revision ID: d480a6c91280
Revises: 8e84bdd311a2
Create Date: 2025-07-22 14:26:50.696402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd480a6c91280'
down_revision = '8e84bdd311a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CartItems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('KichThuoc', sa.Unicode(length=10, collation='Vietnamese_CI_AS'), server_default=sa.text("'M'"), nullable=False))
        batch_op.add_column(sa.Column('MauSac', sa.Unicode(length=30, collation='Vietnamese_CI_AS'), server_default=sa.text("'Trắng'"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CartItems', schema=None) as batch_op:
        batch_op.drop_column('MauSac')
        batch_op.drop_column('KichThuoc')

    # ### end Alembic commands ###
