"""thêm cột cho bảng Product  

Revision ID: e5eb5aff0c52
Revises: 28dbb3baae1d
Create Date: 2025-08-11 21:31:30.954346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5eb5aff0c52'
down_revision = '28dbb3baae1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DiemDanhGia', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.drop_column('DiemDanhGia')

    # ### end Alembic commands ###
