"""thêm bảng order tạm 

Revision ID: f7db58bad85e
Revises: c0dcf2156ded
Create Date: 2025-07-29 20:34:00.794818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7db58bad85e'
down_revision = 'c0dcf2156ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PendingOrders',
    sa.Column('MaDonHangTam', sa.String(length=100), nullable=False),
    sa.Column('MaNguoiDung', sa.Integer(), nullable=False),
    sa.Column('ThongTinDonHang', sa.JSON(), nullable=False),
    sa.Column('ChiTietDonHang', sa.JSON(), nullable=False),
    sa.Column('NgayTao', sa.DateTime(), server_default=sa.text('(getdate())'), nullable=False),
    sa.ForeignKeyConstraint(['MaNguoiDung'], ['Users.MaNguoiDung'], name='FK__PendingOrders__MaNguoiDung'),
    sa.PrimaryKeyConstraint('MaDonHangTam', name='PK__PendingOrders__MaDonHangTam')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PendingOrders')
    # ### end Alembic commands ###
