"""Thêm 1 bảng UserAdresses 

Revision ID: fbd0b2c446ce
Revises: caa277fa971a
Create Date: 2025-07-25 14:37:47.876717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd0b2c446ce'
down_revision = 'caa277fa971a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserAddresses',
    sa.Column('MaDiaChi', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('MaNguoiDung', sa.Integer(), nullable=False),
    sa.Column('TenNguoiNhan', sa.Unicode(length=100, collation='Vietnamese_CI_AS'), nullable=False),
    sa.Column('SoDienThoai', sa.Unicode(length=20, collation='Vietnamese_CI_AS'), nullable=False),
    sa.Column('DiaChiChiTiet', sa.Unicode(length=255, collation='Vietnamese_CI_AS'), nullable=False),
    sa.Column('QuanHuyen', sa.Unicode(length=100, collation='Vietnamese_CI_AS'), nullable=True),
    sa.Column('TinhThanh', sa.Unicode(length=100, collation='Vietnamese_CI_AS'), nullable=True),
    sa.Column('MacDinh', sa.Boolean(), server_default=sa.text('((0))'), nullable=False),
    sa.Column('NgayTao', sa.DateTime(), server_default=sa.text('(getdate())'), nullable=False),
    sa.ForeignKeyConstraint(['MaNguoiDung'], ['Users.MaNguoiDung'], name='FK__UserAddresses__MaNguoiDung'),
    sa.PrimaryKeyConstraint('MaDiaChi', name='PK__UserAddresses__MaDiaChi')
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('DiaChi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DiaChi', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True))

    op.drop_table('UserAddresses')
    # ### end Alembic commands ###
