"""xóa cột điểm đánh giá

Revision ID: fbd917570cbd
Revises: a740ee590519
Create Date: 2025-09-12 18:58:17.196269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd917570cbd'
down_revision = 'a740ee590519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NguoiDung_MaGiamGia', schema=None) as batch_op:
        batch_op.alter_column(
            'MaUserCoupon',  # tên cột cũ
            new_column_name='MaNguoiDungGiamGia'
        )

    with op.batch_alter_table('SanPham', schema=None) as batch_op:
        batch_op.drop_column('DiemDanhGia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SanPham', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DiemDanhGia', sa.FLOAT(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('NguoiDung_MaGiamGia', schema=None) as batch_op:
        batch_op.alter_column(
            'MaUserCoupon',
            new_column_name='MaNguoiDungGiamGia'
        )

    # ### end Alembic commands ###
