"""Thê 

Revision ID: fcb703ecddf2
Revises: c8d28ed10bb1
Create Date: 2025-07-28 16:55:14.726613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb703ecddf2'
down_revision = 'c8d28ed10bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MaDiaChi', sa.Integer(), server_default=sa.text("'1'"), nullable=True))
        batch_op.create_foreign_key('FK__Orders__MaDiaChi', 'UserAddresses', ['MaDiaChi'], ['MaDiaChi'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.drop_constraint('FK__Orders__MaDiaChi', type_='foreignkey')
        batch_op.drop_column('MaDiaChi')

    # ### end Alembic commands ###
